config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :activities
  resources :instructors
  resources :programs
  devise_for :users
  root 'welcome#index'
end

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Adeco</a>
    <ul class="nav navbar-nav">
      <% if user_signed_in? %>
        <li class="active">
          <a href="<%= root_path %>">Home</a>
        </li>
        <li>
          <a href="<%= activities_path %>">Actividades</a>
        </li>
       <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administrador <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="<%= programs_path %>">Programas de formación</a></li>
            <li><a href="<%= instructors_path %>">Instructores</a></li>
            <li><a href="<%= items_path %>">Productos</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>        
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete  %></li>
        <% else %>
        <li><%= link_to "Iniciar sesión", new_user_session_path  %></li>
        
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Adeco</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!--   <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
 -->
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <%= render 'layouts/menu' %>
      </div>
    </div>
    <%= yield %>
  </div>

</body>
</html>